version: '3.7'

services:
  spark-master:
    build: my-spark-image 
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network

  spark-worker:
    build: my-spark-image 
    # container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081-8088:8081"
      - "4040-4050:4040"
    scale: 3
    networks:
      - spark-network

  spark-history-server:
    build: my-spark-image 
    container_name: spark-history-server
    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/spark-logs -Dspark.history.ui.port=18080
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./spark-logs:/opt/spark-logs
    ports:
      - "18080:18080"
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
