version: '3.7'

services:
  spark-master:
    build: .
    image: custom-spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_EVENT_LOG_ENABLED=true
      - SPARK_EVENT_LOG_DIR=/tmp/spark-events
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark-logs:/tmp/spark-events

  spark-worker:
    build: .
    image: custom-spark:latest 
    # container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_EVENT_LOG_ENABLED=true
      - SPARK_EVENT_LOG_DIR=/tmp/spark-events
    volumes:
      - ./spark-logs:/tmp/spark-events
    depends_on:
      - spark-master
    ports:
      - "8081-8088:8081"
    scale: 3

  spark-history-server:
    image: custom-spark:latest
    container_name: spark-history-server
    hostname: spark-history-server
    environment:
      - SPARK_MODE=history
      - SPARK_HISTORY_FS_LOGDIRECTORY=/tmp/spark-events
    ports:
      - "18080:18080"
    volumes:
      - ./spark-logs:/tmp/spark-events
    depends_on:
      - spark-master
    

